name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/crypto:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/crypto:latest

      - name: Run Docker container
        run: |
          docker run ghcr.io/${{ github.repository }}/crypto:latest
